//! Raw FFI bindings to the C++/XRT shim (`shim/npu_shim.h`), generated by
//! `build.rs` with bindgen. See [`crate::npu`] for the safe wrapper.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
