use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let shaders_dir = Path::new(&manifest_dir).join("shaders");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", shaders_dir.display());

    let mut shaders: Vec<(String, u64)> = Vec::new();

    let entries = fs::read_dir(&shaders_dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", shaders_dir.display(), e));

    for entry in entries {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|s| s.to_str()) != Some("slang") {
            continue;
        }

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("non-utf8 filename: {}", path.display()))
            .to_owned();

        println!("cargo:rerun-if-changed={}", path.display());

        let spv_path = out_dir.join(format!("{stem}.spv"));

        let status = Command::new("slangc")
            .arg(&path)
            .args([
                "-target",
                "spirv",
                "-emit-spirv-directly",
                "-fvk-use-entrypoint-name",
                "-o",
            ])
            .arg(&spv_path)
            .status()
            .unwrap_or_else(|e| panic!("failed to spawn slangc for {}: {e}", path.display()));

        if !status.success() {
            panic!(
                "slangc failed for {} (exit {:?})",
                path.display(),
                status.code()
            );
        }

        let size = fs::metadata(&spv_path)
            .unwrap_or_else(|e| panic!("failed to stat {}: {e}", spv_path.display()))
            .len();

        if size == 0 || size % 4 != 0 {
            panic!(
                "compiled SPIR-V {} has unexpected size {} (must be non-zero, multiple of 4)",
                spv_path.display(),
                size
            );
        }

        shaders.push((stem, size));
    }

    shaders.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. Do not edit.\n");
    out.push_str("use core::ops::Deref;\n\n");
    out.push_str("#[repr(C, align(4))]\n");
    out.push_str("pub struct Aligned4<const N: usize>(pub [u8; N]);\n\n");
    out.push_str("impl<const N: usize> Aligned4<N> {\n");
    out.push_str("    pub const fn as_bytes(&self) -> &[u8] { &self.0 }\n");
    out.push_str("}\n");
    out.push_str("impl<const N: usize> Deref for Aligned4<N> {\n");
    out.push_str("    type Target = [u8];\n");
    out.push_str("    fn deref(&self) -> &[u8] { &self.0 }\n");
    out.push_str("}\n");
    out.push_str("impl<const N: usize> AsRef<[u8]> for Aligned4<N> {\n");
    out.push_str("    fn as_ref(&self) -> &[u8] { &self.0 }\n");
    out.push_str("}\n\n");

    for (stem, size) in &shaders {
        let upper = stem.to_uppercase();
        writeln!(
            out,
            "pub static {upper}_SPV: Aligned4<{size}> = \
             Aligned4(*include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}.spv\")));"
        )
        .unwrap();
    }

    fs::write(out_dir.join("shaders.rs"), out).expect("write shaders.rs");
}
