use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    ensure_git_hooks_path(&manifest_dir);
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    println!("cargo:rerun-if-changed=build.rs");
    generate_public_assets(&manifest_dir, &out_dir);
}

/// Point git at the source-controlled hooks in `.githooks/` (the Rust analog of
/// an npm `postinstall` hook install — build scripts always run once on a fresh
/// clone before any cache exists). Best-effort and idempotent: skips outside a
/// git work tree (vendored/release builds with no `.git`), skips if git is
/// missing, and never clobbers an already-set `core.hooksPath`. Bypass any
/// single push with `git push --no-verify`.
///
/// In the workspace, this build script lives in a member crate
/// (`apps/seeker-cli`), so `CARGO_MANIFEST_DIR` is a subdirectory of the repo,
/// not the git top level. Resolve the top level with `git rev-parse` before
/// touching `core.hooksPath` (which is set relative to the repo root).
fn ensure_git_hooks_path(manifest_dir: &str) {
    // Resolve the git work-tree top level from the crate dir. Fails (and we
    // bail) when this isn't a git checkout — e.g. a vendored/release build.
    let toplevel = match Command::new("git")
        .args(["-C", manifest_dir, "rev-parse", "--show-toplevel"])
        .output()
    {
        Ok(out) if out.status.success() => String::from_utf8_lossy(&out.stdout).trim().to_string(),
        _ => return,
    };
    if toplevel.is_empty() {
        return;
    }
    // Only configure when unset — respect a deliberate override.
    if let Ok(out) = Command::new("git")
        .args(["-C", &toplevel, "config", "--get", "core.hooksPath"])
        .output()
        && out.status.success()
        && !out.stdout.is_empty()
    {
        return;
    }
    if Command::new("git")
        .args(["-C", &toplevel, "config", "core.hooksPath", ".githooks"])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
    {
        println!("cargo:warning=enabled git pre-push gate (core.hooksPath=.githooks)");
    }
}

/// Walk `<manifest_dir>/public` and generate `<out_dir>/public_assets.rs`: an
/// `Asset` struct plus a `lookup(path) -> Option<Asset>` over forward-slash
/// relative paths, each arm an `include_bytes!` of the source-tree file so the
/// whole tree is baked into the binary. An absent or empty `public/` yields a
/// `lookup` that always returns `None`.
fn generate_public_assets(manifest_dir: &str, out_dir: &Path) {
    let public_dir = Path::new(manifest_dir).join("public");

    // Re-run when the directory's membership changes (a file added/removed).
    // Cargo tolerates a non-existent path here, so a later `mkdir public` still
    // triggers regeneration. Content *edits* are tracked separately by rustc via
    // the generated `include_bytes!`, so they need no build.rs rerun.
    println!("cargo:rerun-if-changed={}", public_dir.display());

    let mut rel_paths: Vec<String> = Vec::new();
    if public_dir.is_dir() {
        collect_assets(&public_dir, &public_dir, &mut rel_paths);
    }
    // Sort for deterministic, byte-reproducible output (matches the shader gen).
    rel_paths.sort();

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. Do not edit.\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("pub struct Asset {\n");
    out.push_str("    pub bytes: &'static [u8],\n");
    out.push_str("    pub content_type: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str("/// Look up an embedded asset by its forward-slash relative path\n");
    out.push_str("/// (no leading slash), e.g. \"index.html\" or \"assets/app.js\".\n");
    out.push_str("pub fn lookup(path: &str) -> Option<Asset> {\n");
    out.push_str("    let asset = match path {\n");
    for rel in &rel_paths {
        let ct = content_type_for(rel);
        // `{rel:?}` / `{ct:?}` Debug-format the `&str` into correctly-escaped,
        // quoted Rust string literals.
        writeln!(
            out,
            "        {rel:?} => Asset {{ bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/public/\", {rel:?})), content_type: {ct:?} }},"
        )
        .unwrap();
    }
    out.push_str("        _ => return None,\n");
    out.push_str("    };\n");
    out.push_str("    Some(asset)\n");
    out.push_str("}\n");

    fs::write(out_dir.join("public_assets.rs"), out).expect("write public_assets.rs");
}

/// Recursively collect regular files under `dir`, keyed by their path relative
/// to `root` and normalized to forward slashes. Skips dotfiles / dot-dirs
/// (`.gitkeep`, `.DS_Store`, `.git`, …).
fn collect_assets(root: &Path, dir: &Path, out: &mut Vec<String>) {
    // Watch this directory so adding/removing a child re-runs build.rs.
    println!("cargo:rerun-if-changed={}", dir.display());

    let entries =
        fs::read_dir(dir).unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("dir entry").path();
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("non-utf8 filename: {}", path.display()));
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect_assets(root, &path, out);
            continue;
        }
        if !path.is_file() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let rel = path
            .strip_prefix(root)
            .expect("descendant of root")
            .to_str()
            .unwrap_or_else(|| panic!("non-utf8 path: {}", path.display()))
            .replace(std::path::MAIN_SEPARATOR, "/");
        // A quote/backslash in a filename would break the generated string
        // literal and the POSIX include path; reject such pathological names.
        assert!(
            !rel.contains('"') && !rel.contains('\\'),
            "asset path contains illegal char: {rel}"
        );
        out.push(rel);
    }
}

/// Map a file's extension to a static content-type string at build time.
fn content_type_for(rel: &str) -> &'static str {
    let ext = rel
        .rsplit('.')
        .next()
        .filter(|e| !e.contains('/')) // dotless filename -> no real extension
        .map(str::to_ascii_lowercase)
        .unwrap_or_default();
    match ext.as_str() {
        "html" | "htm" => "text/html; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml; charset=utf-8",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "wasm" => "application/wasm",
        "txt" => "text/plain; charset=utf-8",
        "xml" => "application/xml; charset=utf-8",
        "pdf" => "application/pdf",
        _ => "application/octet-stream",
    }
}
